//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangES {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LangES() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Properties.Langs.LangES", typeof(LangES).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get your first win!.
        /// </summary>
        public static string ach1 {
            get {
                return ResourceManager.GetString("ach1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get 10 wins!!.
        /// </summary>
        public static string ach2 {
            get {
                return ResourceManager.GetString("ach2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Congratulations, 250 victories!!!.
        /// </summary>
        public static string ach3 {
            get {
                return ResourceManager.GetString("ach3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a make two friends.
        /// </summary>
        public static string ach4 {
            get {
                return ResourceManager.GetString("ach4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a first loss?.
        /// </summary>
        public static string ach5 {
            get {
                return ResourceManager.GetString("ach5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acept.
        /// </summary>
        public static string btnAcept {
            get {
                return ResourceManager.GetString("btnAcept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Achievement.
        /// </summary>
        public static string btnAchievement {
            get {
                return ResourceManager.GetString("btnAchievement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add.
        /// </summary>
        public static string btnAdd {
            get {
                return ResourceManager.GetString("btnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string btnBack {
            get {
                return ResourceManager.GetString("btnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string btnCancel {
            get {
                return ResourceManager.GetString("btnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Chat.
        /// </summary>
        public static string btnChat {
            get {
                return ResourceManager.GetString("btnChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Continue.
        /// </summary>
        public static string btnContinue {
            get {
                return ResourceManager.GetString("btnContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delet Friend.
        /// </summary>
        public static string btnDeletFriend {
            get {
                return ResourceManager.GetString("btnDeletFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string btnExit {
            get {
                return ResourceManager.GetString("btnExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Forgot Password.
        /// </summary>
        public static string btnForgotPassword {
            get {
                return ResourceManager.GetString("btnForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friends.
        /// </summary>
        public static string btnFriends {
            get {
                return ResourceManager.GetString("btnFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string btnLogin {
            get {
                return ResourceManager.GetString("btnLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log out.
        /// </summary>
        public static string btnLogOut {
            get {
                return ResourceManager.GetString("btnLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Account.
        /// </summary>
        public static string btnNewAccount {
            get {
                return ResourceManager.GetString("btnNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Room.
        /// </summary>
        public static string btnNewRoom {
            get {
                return ResourceManager.GetString("btnNewRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        public static string btnNext {
            get {
                return ResourceManager.GetString("btnNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Personalize.
        /// </summary>
        public static string btnPersonalize {
            get {
                return ResourceManager.GetString("btnPersonalize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ranking.
        /// </summary>
        public static string btnRanking {
            get {
                return ResourceManager.GetString("btnRanking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Recharge.
        /// </summary>
        public static string btnRecharge {
            get {
                return ResourceManager.GetString("btnRecharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Refuse.
        /// </summary>
        public static string btnRefuse {
            get {
                return ResourceManager.GetString("btnRefuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Request.
        /// </summary>
        public static string btnRequest {
            get {
                return ResourceManager.GetString("btnRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Restore Background.
        /// </summary>
        public static string btnRestoreBackground {
            get {
                return ResourceManager.GetString("btnRestoreBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search.
        /// </summary>
        public static string btnSearch {
            get {
                return ResourceManager.GetString("btnSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send.
        /// </summary>
        public static string btnSend {
            get {
                return ResourceManager.GetString("btnSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Code.
        /// </summary>
        public static string btnSendCode {
            get {
                return ResourceManager.GetString("btnSendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Game.
        /// </summary>
        public static string btnStartGame {
            get {
                return ResourceManager.GetString("btnStartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Surrender.
        /// </summary>
        public static string btnSurrender {
            get {
                return ResourceManager.GetString("btnSurrender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string EN {
            get {
                return ResourceManager.GetString("EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string ES {
            get {
                return ResourceManager.GetString("ES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a AFEL.
        /// </summary>
        public static string lbAFEL {
            get {
                return ResourceManager.GetString("lbAFEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat Password.
        /// </summary>
        public static string lbAgainPassword {
            get {
                return ResourceManager.GetString("lbAgainPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose a difficulty.
        /// </summary>
        public static string lbChooseDifficulty {
            get {
                return ResourceManager.GetString("lbChooseDifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Choose a section.
        /// </summary>
        public static string lbChooseSection {
            get {
                return ResourceManager.GetString("lbChooseSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Easy (4x4).
        /// </summary>
        public static string lbEasy {
            get {
                return ResourceManager.GetString("lbEasy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string lbEmail {
            get {
                return ResourceManager.GetString("lbEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Friend Requests.
        /// </summary>
        public static string lbFriendRequest {
            get {
                return ResourceManager.GetString("lbFriendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hard (8x8).
        /// </summary>
        public static string lbHard {
            get {
                return ResourceManager.GetString("lbHard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Invite your friend.
        /// </summary>
        public static string lbInviteFriend {
            get {
                return ResourceManager.GetString("lbInviteFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a -Language-.
        /// </summary>
        public static string lbLanguage {
            get {
                return ResourceManager.GetString("lbLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string lbLogin {
            get {
                return ResourceManager.GetString("lbLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        public static string lbNewPassword {
            get {
                return ResourceManager.GetString("lbNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No.
        /// </summary>
        public static string lbNo {
            get {
                return ResourceManager.GetString("lbNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Normal (6x6).
        /// </summary>
        public static string lbNormal {
            get {
                return ResourceManager.GetString("lbNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string lbPassword {
            get {
                return ResourceManager.GetString("lbPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player.
        /// </summary>
        public static string lbPlayer {
            get {
                return ResourceManager.GetString("lbPlayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Player Turn:.
        /// </summary>
        public static string lbPlayerTurn {
            get {
                return ResourceManager.GetString("lbPlayerTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remaining Pairs:.
        /// </summary>
        public static string lbRemainingPairs {
            get {
                return ResourceManager.GetString("lbRemainingPairs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Room.
        /// </summary>
        public static string lbRoom {
            get {
                return ResourceManager.GetString("lbRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Score:.
        /// </summary>
        public static string lbScore {
            get {
                return ResourceManager.GetString("lbScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Search Friend.
        /// </summary>
        public static string lbSearchFriend {
            get {
                return ResourceManager.GetString("lbSearchFriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Settings.
        /// </summary>
        public static string lbSettings {
            get {
                return ResourceManager.GetString("lbSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sound:.
        /// </summary>
        public static string lbSound {
            get {
                return ResourceManager.GetString("lbSound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Study.
        /// </summary>
        public static string lbStudy {
            get {
                return ResourceManager.GetString("lbStudy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Time:.
        /// </summary>
        public static string lbTime {
            get {
                return ResourceManager.GetString("lbTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a TOP.
        /// </summary>
        public static string lbTop {
            get {
                return ResourceManager.GetString("lbTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To Refuse.
        /// </summary>
        public static string lbToRefuse {
            get {
                return ResourceManager.GetString("lbToRefuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Victories.
        /// </summary>
        public static string lbVictories {
            get {
                return ResourceManager.GetString("lbVictories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Visual:.
        /// </summary>
        public static string lbVisual {
            get {
                return ResourceManager.GetString("lbVisual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Yes.
        /// </summary>
        public static string lbYes {
            get {
                return ResourceManager.GetString("lbYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Select your favorite background!.
        /// </summary>
        public static string textBackground {
            get {
                return ResourceManager.GetString("textBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter the code sent to your email.
        /// </summary>
        public static string textCode {
            get {
                return ResourceManager.GetString("textCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure you want to exit the game?.
        /// </summary>
        public static string textGameExit {
            get {
                return ResourceManager.GetString("textGameExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Which nametag would you like?.
        /// </summary>
        public static string textNametag {
            get {
                return ResourceManager.GetString("textNametag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Welcome to the game:.
        /// </summary>
        public static string textWelcome {
            get {
                return ResourceManager.GetString("textWelcome", resourceCulture);
            }
        }
    }
}
