//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.PreGameService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PreGameService.IChatService", CallbackContract=typeof(Client.PreGameService.IChatServiceCallback))]
    public interface IChatService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Join")]
        void Join(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Join")]
        System.Threading.Tasks.Task JoinAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendMessage")]
        void SendMessage(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/SendMessage")]
        System.Threading.Tasks.Task SendMessageAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Leave")]
        void Leave(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/Leave")]
        System.Threading.Tasks.Task LeaveAsync(string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/PrivateSendMessage")]
        void PrivateSendMessage(string message, string username);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/PrivateSendMessage")]
        System.Threading.Tasks.Task PrivateSendMessageAsync(string message, string username);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/RecieveMessage")]
        void RecieveMessage(string user, string message);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IChatService/UsersUpdate")]
        void UsersUpdate(System.Collections.Generic.Dictionary<object, string>.ValueCollection users);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IChatServiceChannel : Client.PreGameService.IChatService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ChatServiceClient : System.ServiceModel.DuplexClientBase<Client.PreGameService.IChatService>, Client.PreGameService.IChatService {
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public ChatServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void Join(string username) {
            base.Channel.Join(username);
        }
        
        public System.Threading.Tasks.Task JoinAsync(string username) {
            return base.Channel.JoinAsync(username);
        }
        
        public void SendMessage(string message) {
            base.Channel.SendMessage(message);
        }
        
        public System.Threading.Tasks.Task SendMessageAsync(string message) {
            return base.Channel.SendMessageAsync(message);
        }
        
        public void Leave(string username) {
            base.Channel.Leave(username);
        }
        
        public System.Threading.Tasks.Task LeaveAsync(string username) {
            return base.Channel.LeaveAsync(username);
        }
        
        public void PrivateSendMessage(string message, string username) {
            base.Channel.PrivateSendMessage(message, username);
        }
        
        public System.Threading.Tasks.Task PrivateSendMessageAsync(string message, string username) {
            return base.Channel.PrivateSendMessageAsync(message, username);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PreGameService.IRoomService", CallbackContract=typeof(Client.PreGameService.IRoomServiceCallback))]
    public interface IRoomService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRoomService/ConnectWaitingRoom")]
        void ConnectWaitingRoom(string userGameConnect);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRoomService/ConnectWaitingRoom")]
        System.Threading.Tasks.Task ConnectWaitingRoomAsync(string userGameConnect);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRoomService/DisconnectRoom")]
        void DisconnectRoom(string usergame);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRoomService/DisconnectRoom")]
        System.Threading.Tasks.Task DisconnectRoomAsync(string usergame);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRoomService/SendInvitation")]
        void SendInvitation(string usergameApplicant, string usergameReceiver);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRoomService/SendInvitation")]
        System.Threading.Tasks.Task SendInvitationAsync(string usergameApplicant, string usergameReceiver);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRoomService/SendAcceptance")]
        void SendAcceptance(string usergameApplicant, string usergameReceiver);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRoomService/SendAcceptance")]
        System.Threading.Tasks.Task SendAcceptanceAsync(string usergameApplicant, string usergameReceiver);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRoomService/RecieveInvitation")]
        void RecieveInvitation(string usergameApplicant);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IRoomService/RecieveAnswer")]
        void RecieveAnswer();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoomServiceChannel : Client.PreGameService.IRoomService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoomServiceClient : System.ServiceModel.DuplexClientBase<Client.PreGameService.IRoomService>, Client.PreGameService.IRoomService {
        
        public RoomServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public RoomServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public RoomServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RoomServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public RoomServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ConnectWaitingRoom(string userGameConnect) {
            base.Channel.ConnectWaitingRoom(userGameConnect);
        }
        
        public System.Threading.Tasks.Task ConnectWaitingRoomAsync(string userGameConnect) {
            return base.Channel.ConnectWaitingRoomAsync(userGameConnect);
        }
        
        public void DisconnectRoom(string usergame) {
            base.Channel.DisconnectRoom(usergame);
        }
        
        public System.Threading.Tasks.Task DisconnectRoomAsync(string usergame) {
            return base.Channel.DisconnectRoomAsync(usergame);
        }
        
        public void SendInvitation(string usergameApplicant, string usergameReceiver) {
            base.Channel.SendInvitation(usergameApplicant, usergameReceiver);
        }
        
        public System.Threading.Tasks.Task SendInvitationAsync(string usergameApplicant, string usergameReceiver) {
            return base.Channel.SendInvitationAsync(usergameApplicant, usergameReceiver);
        }
        
        public void SendAcceptance(string usergameApplicant, string usergameReceiver) {
            base.Channel.SendAcceptance(usergameApplicant, usergameReceiver);
        }
        
        public System.Threading.Tasks.Task SendAcceptanceAsync(string usergameApplicant, string usergameReceiver) {
            return base.Channel.SendAcceptanceAsync(usergameApplicant, usergameReceiver);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PreGameService.IPreGameService", CallbackContract=typeof(Client.PreGameService.IPreGameServiceCallback))]
    public interface IPreGameService {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPreGameService/ConnectPlayer")]
        void ConnectPlayer(string usergameConnected, string usergameAdmin);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPreGameService/ConnectPlayer")]
        System.Threading.Tasks.Task ConnectPlayerAsync(string usergameConnected, string usergameAdmin);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPreGameService/DisconnectPlayer")]
        void DisconnectPlayer(string usergameToDisconnect, string usergameToNotify);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPreGameService/DisconnectPlayer")]
        System.Threading.Tasks.Task DisconnectPlayerAsync(string usergameToDisconnect, string usergameToNotify);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPreGameService/SendAccessGame")]
        void SendAccessGame(string usergam1, string usergame2);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPreGameService/SendAccessGame")]
        System.Threading.Tasks.Task SendAccessGameAsync(string usergam1, string usergame2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPreGameServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPreGameService/UpdateUsersRoom")]
        void UpdateUsersRoom(System.Collections.Generic.Dictionary<object, string>.ValueCollection usersPreGame);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPreGameService/RecieveAccessGame")]
        void RecieveAccessGame();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IPreGameService/RecieveExitNotification")]
        void RecieveExitNotification(string userDisconnected);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPreGameServiceChannel : Client.PreGameService.IPreGameService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PreGameServiceClient : System.ServiceModel.DuplexClientBase<Client.PreGameService.IPreGameService>, Client.PreGameService.IPreGameService {
        
        public PreGameServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public PreGameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public PreGameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PreGameServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public PreGameServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public void ConnectPlayer(string usergameConnected, string usergameAdmin) {
            base.Channel.ConnectPlayer(usergameConnected, usergameAdmin);
        }
        
        public System.Threading.Tasks.Task ConnectPlayerAsync(string usergameConnected, string usergameAdmin) {
            return base.Channel.ConnectPlayerAsync(usergameConnected, usergameAdmin);
        }
        
        public void DisconnectPlayer(string usergameToDisconnect, string usergameToNotify) {
            base.Channel.DisconnectPlayer(usergameToDisconnect, usergameToNotify);
        }
        
        public System.Threading.Tasks.Task DisconnectPlayerAsync(string usergameToDisconnect, string usergameToNotify) {
            return base.Channel.DisconnectPlayerAsync(usergameToDisconnect, usergameToNotify);
        }
        
        public void SendAccessGame(string usergam1, string usergame2) {
            base.Channel.SendAccessGame(usergam1, usergame2);
        }
        
        public System.Threading.Tasks.Task SendAccessGameAsync(string usergam1, string usergame2) {
            return base.Channel.SendAccessGameAsync(usergam1, usergame2);
        }
    }
}
